{% set name = "discord.py" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 173b5e2fea2e012bbe964e87e92826ccaf97056bba539a7caec988f329acca04

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - aiohttp >=3.3.0,<3.6.0
    - pip
    - python
    - websockets >=6.0,<7.0
  run:
    - aiohttp >=3.3.0,<3.6.0
    - python
    - websockets >=6.0,<7.0

test:
  imports:
    - discord
    - discord.ext.commands

about:
  home: https://github.com/Rapptz/discord.py
  license: MIT
  license_family: MIT
  license_file: 
  summary: A python wrapper for the Discord API
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - cjmartian
